"$schema" = 'https://starship.rs/config-schema.json'


format = """
[î‚¶](color_orange)\
$os\
$username\
${custom.isWork}\
[î‚´](bg:color_yellow fg:color_orange)\
$directory\
[î‚´](fg:color_yellow bg:color_aqua)\
${custom.giturl}\
$git_branch\
$git_status\
[î‚´](fg:color_aqua bg:color_blue)\
$kubernetes\
$docker\
$golang\
$python\
[î‚´](fg:color_blue bg:color_bg3)\
$docker_context\
$direnv$container\
[î‚´](fg:color_bg3 bg:color_bg1)\
$fill\
${custom.live-clock-icon}\
$time \
\n$sudo$character\
"""

right_format = """
$cmd_duration\
$singularity\
$memory_usage
"""
continuation_prompt =  'â–¶â–¶ '

palette = 'gruvbox_dark'

# [direnv]
# disabled = false
# symbol = ""
# format = "[$allowed]($style)"
# allowed_msg = ' ó±¥¾ '
# style = "bg:color_bg3"

[singularity]
format = 'î¶•[\[$env\]]($style) '

[cmd_duration]
format = '[ó°¾¨ $duration ]($style)'
style = 'fg:color_red'
min_time = 500
disabled = false


[sudo]
format = "[$symbol]($style)"
symbol = "ğŸ§™"
disabled = false

[fill]
symbol = " "

[custom.isWork]
when = "git config --get core.isWork | grep -q true"
style="bg:color_orange"
symbol="ğŸ’¼ "
require_repo = true

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg0_h = '#1d2021'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ïŒ›"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "ó°‡˜/"
read_only = 'ó°‰ '
use_os_path_sep= true

[memory_usage]
symbol = ' î¿… !'
threshold = 75
disabled = false

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git config --get remote.origin.url)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="î—» "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL"
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "fg:color_bg0_h bg:color_aqua"
format = "[ $output ]($style)"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
"dotfiles" = ".ï€“"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "î™"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = "î˜†"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[terraform]
style = "bg:color_blue"
symbol = "îšš"
format = "[ $symbol ]($style)"

[docker_context]
symbol = "ïŒˆ"
style = "bg:color_bg0_h"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg0_h)]($style)'

[time]
disabled = false
time_format = "%R"
style = ""
format = '[$time]($style)'

[character]
# The name of the module we arconfiguring is "character"
disabled = false
success_symbol = '[Î¶](bold fg:color_green)'
error_symbol = '[ï‘§ ](bold fg:color_red)'
vimcmd_symbol = '[îŸ…](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ó±¦»](bold fg:color_purple)'
vimcmd_replace_symbol = '[î©³](bold fg:color_purple)'
vimcmd_visual_symbol = '[ó°¸±](bold fg:color_yellow)'
format = ' $symbol '

# https://github.com/starship/starship/discussions/1252#discussioncomment-9914579
[custom.live-clock-icon]
command = 'h="îî‚îƒî„î…î†î‡îˆî‰îŠî‹îŒ";echo ${h:$(date +%H)%12:1}'
description = "Live updating clock icon, changes hourly. Icons can be customized to your liking."
when = true
style = "fg: color_fg0"
format = "[$output ]($style)"

